# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vibevid < Formula
  desc "Coding Education Video Scene Generator for creating short, high-energy explainer videos from a script."
  homepage "https://github.com/shayyz-code/vibevid-cli"
  version "0.1.2"
  license "MIT"

  depends_on "bun"
  depends_on "ffmpeg"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shayyz-code/vibevid-cli/releases/download/v0.1.2/vibevid_Darwin_x86_64.tar.gz"
      sha256 "5039d8a275231bdfd777991ff05d075d830d151ec591f3819fc7e9177790678f"

      define_method(:install) do
        bin.install "vibevid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shayyz-code/vibevid-cli/releases/download/v0.1.2/vibevid_Darwin_arm64.tar.gz"
      sha256 "a8d5c11f79537ce4b4b8a7a60f255aeabdcf006cedff4f81a594539a8a32e4aa"

      define_method(:install) do
        bin.install "vibevid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shayyz-code/vibevid-cli/releases/download/v0.1.2/vibevid_Linux_x86_64.tar.gz"
      sha256 "aa2cd77d996b0f0e50881f0ca0eb1540c306b39c6f449550d86e8e341e0e49bc"
      define_method(:install) do
        bin.install "vibevid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shayyz-code/vibevid-cli/releases/download/v0.1.2/vibevid_Linux_arm64.tar.gz"
      sha256 "1ee7d670ebd9106d9e6ddb36b99b3af5bc14583f80eee1d205b0b91ddeb9eb73"
      define_method(:install) do
        bin.install "vibevid"
      end
    end
  end

  test do
    system "#{bin}/vibevid", "--help"
  end
end
