# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jellycord < Formula
  desc "CLI chat client for Jellycord"
  homepage "https://github.com/shayyz-code/jellycord"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shayyz-code/jellycord/releases/download/v0.1.1/jellycord_darwin_x86_64.tar.gz"
      sha256 "29ddfc42aa15194cb2507095832be6e258bf7cb988ca0584bcc8588a9d94074f"

      define_method(:install) do
        bin.install "jellycord"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shayyz-code/jellycord/releases/download/v0.1.1/jellycord_darwin_arm64.tar.gz"
      sha256 "c5118a1570049e06dd87bc9df3104b77aed0ebd9784ff55dc9daf6f593d81f9b"

      define_method(:install) do
        bin.install "jellycord"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shayyz-code/jellycord/releases/download/v0.1.1/jellycord_linux_x86_64.tar.gz"
      sha256 "5a3895d3557fa0332e981d78803b41adc0e924fa3cafe1c63b925782714b519d"
      define_method(:install) do
        bin.install "jellycord"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shayyz-code/jellycord/releases/download/v0.1.1/jellycord_linux_arm64.tar.gz"
      sha256 "4566bfc34f6a4920e0baa6c6c6bf82d7a3a7eed3d56e131d947c4b3bec6d6a9a"
      define_method(:install) do
        bin.install "jellycord"
      end
    end
  end
end
