# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JsonFirestoreSeed < Formula
  desc "Seed Firestore with JSON data easily."
  homepage "https://github.com/shayyz-code/json-firestore-seed"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shayyz-code/json-firestore-seed/releases/download/v0.1.7/json-firestore-seed_0.1.7_darwin_amd64.tar.gz"
      sha256 "e48d7f9f7a9f133035ef2106871af389850a790a9620be8c1481d2eb813a5743"

      define_method(:install) do
        bin.install "json-firestore-seed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shayyz-code/json-firestore-seed/releases/download/v0.1.7/json-firestore-seed_0.1.7_darwin_arm64.tar.gz"
      sha256 "658bfcc8a7ab3bf07327a4c11758322f023b7362431ceb79f4754c3a12b84d2e"

      define_method(:install) do
        bin.install "json-firestore-seed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shayyz-code/json-firestore-seed/releases/download/v0.1.7/json-firestore-seed_0.1.7_linux_amd64.tar.gz"
      sha256 "3e950d218e357b948f0591b6eecb57886eeca3152e6d577ca3807cce18018a89"
      define_method(:install) do
        bin.install "json-firestore-seed"
      end
    end
  end

  test do
    system "#{bin}/json-firestore-seed --version"
  end
end
