# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JsonFirestoreSeed < Formula
  desc "Seed Firestore with JSON data easily."
  homepage "https://github.com/shayyz-code/json-firestore-seed"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shayyz-code/json-firestore-seed/releases/download/v0.1.8/json-firestore-seed_0.1.8_darwin_amd64.tar.gz"
      sha256 "2d582fd2a461b8bbb4e1573878fd451046ba7b3fe66ea24bd3202037a89b2b1a"

      define_method(:install) do
        bin.install "json-firestore-seed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shayyz-code/json-firestore-seed/releases/download/v0.1.8/json-firestore-seed_0.1.8_darwin_arm64.tar.gz"
      sha256 "a33afdc0e8bc15f24cedb24c2bae0bdf4c389c8cec3e2adaa7156a2f6cb8b7d1"

      define_method(:install) do
        bin.install "json-firestore-seed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shayyz-code/json-firestore-seed/releases/download/v0.1.8/json-firestore-seed_0.1.8_linux_amd64.tar.gz"
      sha256 "2f1c1db004a3559725fdc06888d6e381b73b94bf80e56bd9cb8990b1c7437d19"
      define_method(:install) do
        bin.install "json-firestore-seed"
      end
    end
  end

  test do
    system "#{bin}/json-firestore-seed --version"
  end
end
